### ISSUE TITLE
FileNotFoundError about nerf_synthetic dataset

### ISSUE THREAD

**Issue by 3DV-Coder** [ubc-vision/NFFB#2]
Hi, thank u for sharing open source code about your grate work. 

When I try to run `train_nerf.py`, there are some FileNotFoundError about nerf_synthetic dataset.
such as 
`FileNotFoundError: ./nerf_synthetic/lego/intrinsics.txt not found.`
`FileNotFoundError: ./nerf_synthetic/lego/bbox.txt not found.`
I know that these errors are caused due to original [nerf_synthetic dataset](https://drive.google.com/drive/folders/1JDdLGDruGNXWnM1eqY1FNL9PlStjaKWi) has been modified or in other words, some files (intrinsics.txt，bbox.txt etc. ) have been added.
Therefore, could you provide the modified nerf_synthetic dataset or added files?

**Comment by zhijieW94** [comment]
Hello, thank you for your messages and sorry for my late response. 

Actually, I agree with you that the config files of nerf_synthetic dataset might have different formats. I faced this problem once before. Since I built this repo based on the [ngp_pl](https://github.com/kwea123/ngp_pl), please refer to their settings and datasets. For me, following their instructions worked well in the past.
